name: Create Manifest

inputs:
  image-name:
    description: Name of the image
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: ${{ runner.temp }}/digests
        pattern: digests-*
        merge-multiple: true
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
    - name: Create manifest list and push
      working-directory: ${{ runner.temp }}/digests
      shell: bash
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
        $(printf '${{ inputs.image-name }}@sha256:%s ' *)
    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ inputs.image-name }}:${{ steps.meta.outputs.version }}
