name: Create Manifest
description: Creates and pushes a multi-platform Docker manifest

inputs:
  image-name:
    description: Name of the image
    type: string
    required: true
  raw-tag:
    description: Raw tag value
    type: string
    default: latest
  title:
    description: Custom image title (overrides repository name)
    type: string
    required: false
  description:
    description: Custom image description (overrides repository description)
    type: string
    required: false

runs:
  using: composite
  steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: ${{ runner.temp }}/digests
        pattern: digests-*
        merge-multiple: true
    - name: Raw tag
      id: raw_tag
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ inputs.raw-tag }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=raw,event=workflow_dispatch,value=${{ steps.raw_tag.outputs.lowercase }}
        labels: |
          ${{ inputs.title != '' && format('org.opencontainers.image.title={0}', inputs.title) || '' }}
          ${{ inputs.description != '' && format('org.opencontainers.image.description={0}', inputs.description) || '' }}
    - name: Create manifest list and push
      working-directory: ${{ runner.temp }}/digests
      shell: bash
      run: |
        mapfile -t tags < <(jq -r '.tags[] | "-t\n" + .' <<< "$DOCKER_METADATA_OUTPUT_JSON")
        mapfile -t annotations < <(jq -r '.labels | to_entries[] | "--annotation\nindex:" + .key + "=" + .value' <<< "$DOCKER_METADATA_OUTPUT_JSON")
        images=$(printf '${{ inputs.image-name }}@sha256:%s ' *)

        docker buildx imagetools create "${tags[@]}" "${annotations[@]}" $images
    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ inputs.image-name }}:${{ steps.meta.outputs.version }}
