name: Build Image

inputs:
  platform:
    description: Platform i.e. "linux/amd64", "linux/arm64"
    type: string
    required: true
  image-name:
    description: Name of the image
    type: string
    required: true
  dockerfile:
    description: Dockerfile path
    type: string
    required: true
  raw-tag:
    description: Raw tag value
    type: string
    default: latest

runs:
  using: composite
  steps:
    - name: Prepare
      shell: bash
      run: |
        platform=${{ inputs.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
    - name: Raw tag
      id: raw_tag
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ inputs.raw-tag }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=raw,event=workflow_dispatch,value=${{ steps.raw_tag.outputs.lowercase }}
    - name: Build and push by digest
      id: build
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.actor != 'dependabot[bot]' }}
        context: .
        file: ${{ inputs.dockerfile}}
        platforms: ${{ inputs.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
        outputs: type=image,name=${{ inputs.image-name }},push-by-digest=true,name-canonical=true
        cache-from: type=gha,scope=${{ inputs.dockerfile }}-${{ env.PLATFORM_PAIR }}
        cache-to: type=gha,mode=max,scope=${{ inputs.dockerfile }}-${{ env.PLATFORM_PAIR }}
    - name: Export digest
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
