name: Build Image
description: Build and push Docker image by digest

inputs:
  platform:
    description: Platform i.e. "linux/amd64", "linux/arm64"
    type: string
    required: true
  image-name:
    description: Name of the image
    type: string
    required: true
  dockerfile:
    description: Dockerfile path
    type: string
    required: true
  title:
    description: Custom image title (overrides repository name)
    type: string
    required: false
  description:
    description: Custom image description (overrides repository description)
    type: string
    required: false

runs:
  using: composite
  steps:
    - name: Prepare
      shell: bash
      run: |
        platform=${{ inputs.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
        labels: |
          ${{ inputs.title != '' && format('org.opencontainers.image.title={0}', inputs.title) || '' }}
          ${{ inputs.description != '' && format('org.opencontainers.image.description={0}', inputs.description) || '' }}
        annotations: |
          ${{ inputs.title != '' && format('org.opencontainers.image.title={0}', inputs.title) || '' }}
          ${{ inputs.description != '' && format('org.opencontainers.image.description={0}', inputs.description) || '' }}
    - name: Build and push by digest
      id: build
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.actor != 'dependabot[bot]' }}
        context: .
        file: ${{ inputs.dockerfile}}
        platforms: ${{ inputs.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        provenance: false
        outputs: type=image,name=${{ inputs.image-name }},push-by-digest=true,name-canonical=true,oci-mediatypes=true
        cache-from: type=gha,scope=${{ inputs.dockerfile }}-${{ env.PLATFORM_PAIR }}
        cache-to: type=gha,mode=max,scope=${{ inputs.dockerfile }}-${{ env.PLATFORM_PAIR }}
    - name: Export digest
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
