name: Build Image

inputs:
  platform:
    description: Platform i.e. "linux/amd64", "linux/arm64"
    type: string
    required: true
  image-name:
    description: Name of the image
    type: string
    required: true
  dockerfile:
    description: Dockerfile path
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Prepare
      shell: bash
      run: |
        platform=${{ inputs.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
    - name: Build and push by digest
      id: build
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.actor != 'dependabot[bot]' }}
        context: .
        file: ${{ inputs.dockerfile}}
        platforms: ${{ inputs.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
        outputs: type=image,name=${{ inputs.image-name }},push-by-digest=true,name-canonical=true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
    - name: Export digest
      shell: bash
      run: |
        mkdir -p /tmp/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "/tmp/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: /tmp/digests/*
        if-no-files-found: error
        retention-days: 1
