name: Build PHP Images

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner name i.e. default runner "ubuntu-24.04"
        type: string
        required: true
      platform:
        description: Platform i.e. "linux/amd64", "linux/arm64"
        type: string
        required: true
      image-name:
        description: Image name
        type: string
        required: true
      dockerfile:
        description: Dockerfile path
        type: string
        default: Dockerfile
      cache-key:
        description: Cache key
        type: string
        required: true
      cache-restore-keys:
        description: Cache restore keys list
        type: string
        required: true

jobs:
  build:
    name: Build Image
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make sure cache dir exists
        run: mkdir -p /tmp/.buildx-cache
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ inputs.cache-key }}
          restore-keys: ${{ inputs.cache-restore-keys }}
      - name: Image name
        id: image_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ inputs.image-name }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
            platforms: ${{ inputs.platform }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.1.0
      - name: Build and Push by digest (runtime)
        uses: Ilyes512/github-actions/build-target@0.4.3
        with:
          platform: ${{ inputs.platform }}
          image-name: ${{ steps.image_name.outputs.lowercase }}
          dockerfile: ${{ inputs.dockerfile }}
          target: runtime
      - name: Build and Push by digest (builder)
        uses: Ilyes512/github-actions/build-target@0.4.3
        with:
          platform: ${{ inputs.platform }}
          image-name: ${{ steps.image_name.outputs.lowercase }}
          dockerfile: ${{ inputs.dockerfile }}
          target: builder
      - name: Build and Push by digest (builder_nodejs)
        uses: Ilyes512/github-actions/build-target@0.4.3
        with:
          platform: ${{ inputs.platform }}
          image-name: ${{ steps.image_name.outputs.lowercase }}
          dockerfile: ${{ inputs.dockerfile }}
          target: builder_nodejs
